### PR TITLE
Use `PyErr_SetObject` instead of `PyErr_Format` for `NonUniqueError`

### PR DESCRIPTION
**Pull request by flexatone**

### CODE REVIEW

**Comment by flexatone** [comment]
Oh, and can we get a 0.6.1 release after this change is merged? 0.6.0 at present breaks some StaticFrame tests, and the general StaticFrame requirements do not pin automap, meaning that a fresh environment will grab 0.6.0.

**Comment by brandtbucher** [comment]
Thanks! Now I'll fix PyPy support and make a new release.

**Comment by flexatone** [comment]
Awesome, thanks!

**Comment by brandtbucher** [comment]
[0.6.1](https://github.com/brandtbucher/automap/releases/tag/0.6.1) released, and up on PyPI!

**Pull request merged**
